name: albiruni
description: A wrapper to easily access IIUM's Course Schedule data.
version: 1.4.4
repository: https://github.com/iqfareez/albiruni
issue_tracker: https://github.com/iqfareez/albiruni/issues
topics:
  - scraper
  - iium

funding:
  - https://www.buymeacoffee.com/iqfareez

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0

dependencies:
  html: ^0.15.0
  http: ^1.1.0
  intl: ^0.20.2
